# Generated by Django 5.1.1 on 2024-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_produccion',
            field=models.DateField(),
        ),
    ]
