# Generated by Django 5.1.1 on 2024-11-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_app', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
