# Generated by Django 5.1.1 on 2024-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id_promocion',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
