# Generated by Django 5.1.1 on 2024-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion_app', '0002_alter_promocion_id_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id_promocion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
