# Generated by Django 5.1.1 on 2024-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envios_app', '0002_alter_envio_estado_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='id_envio',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
