# Generated by Django 5.1.1 on 2024-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envios_app', '0003_alter_envio_id_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='id_envio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
