# Generated by Django 5.1.1 on 2024-11-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envios_app', '0004_alter_envio_id_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_envio',
            new_name='fecha_estimada_llegada',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_llegada',
            new_name='fecha_salida',
        ),
        migrations.AddField(
            model_name='envio',
            name='id_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
